name: CI
on: 
  push:
    branches: [ main ]
jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: '17.4.0'
  #     - name: Install dependencies
  #       run: yarn --frozen-lockfile
  #     - run: yarn build
  #     - run: yarn preview
  #     - run: yarn cypress run --port 6969
  
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: yarn build
          start: yarn preview --port 3000
