name: CI
on: 
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17.4.0'
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - run: cypress -v
      - run: yarn build
      - run: yarn cypress run